### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by patrickrobbins** [TallyDotNet/event-site#22]
The Chinese form seems to be an iframe to a google doc that won't load.

**Comment by patrickrobbins** [comment]
*contact form

**Comment by jamescrowley321** [comment]
Are you talking about the one here: http://www.tallycodecamp.org/contact ?

**Comment by patrickrobbins** [comment]
maybe that was some firewall issue.  my bad. I didn't think about the
google forms being blocked
